### ISSUE TITLE
GitHub API rate limit exceeded

### ISSUE THREAD

**Issue by pritikasambyal** [redhat-developer/openshift-vsts#88]
We are receiving error "API rate limit exceeded" when trying to do Openshift deployment using Azure Pipelines. We are using Azure DevOps task for executing OCP commands. Each command is connecting to GitHub and thus our API limit is getting exhausted. Why does OCP establish GitHub connection? 
I found out we can extend the rate limit by passing client Id and secret, how to do the same while using this task?

**Comment by hferentschik** [comment]
Thanks for the issue report.

> We are receiving error "API rate limit exceeded" when trying to do Openshift deployment using Azure Pipelines. We are using Azure DevOps task for executing OCP commands. Each command is connecting to GitHub and thus our API limit is getting exhausted. Why does OCP establish GitHub connection?

The execute command does work also standalone w/o the install command. In this case it transparently downloads the _oc_ binary. Really what's missing here is a check whether the requested version already exist.

Do you explicitly specify the `oc` version? If not, you should. Partly to ensure you get the right/matching version of `oc` and partly because this will reduce the calls to the GitHub API, since now the latest stable version does not need to be discovered anymore.

> I found out we can extend the rate limit by passing client Id and secret, how to do the same while using this task?

You can set the environment variable _GITHUB_ACCESS_TOKEN_ to specify a GitHub token you generate. Then you get a higher rate limit.

**Comment by hferentschik** [comment]
In the context of this issue, the following should happen:

* implement a check whether requested `oc` version is already cached
* document the use of GITHUB_ACCESS_TOKEN

**Comment by hferentschik** [comment]
Another workaround could be the use of the setup task and then executing a range of oc commands within a script.

**Comment by lstocchi** [comment]
One could take advantage of the Cache (Beta) Task and use that for caching. Something like:

```
- task: CacheBeta@0
  inputs:
    key: 'cache'
    path: $(System.DefaultWorkingDirectory)/.download/

- task: oc-cmd@2
  inputs:
    openshiftService: 'My Openshift'
    version: 'v3.11.0'
    cmd: 'oc version'
```

Still not sure if one can create an extension which merge the cache task with oc. Otherwise we should create our own caching system and rely on azure storage to store our blob but azure storage is not free.

**Comment by lstocchi** [comment]
We released the new Openshift VSTS extension and now the oc cli gets downloaded from mirror.openshift.com. There shouldn't be problems with github API anymore. Closing this.
